apiVersion: v1
kind: Service
metadata:
  name: eks-demo-app
  namespace: default
  labels:
    app: eks-demo-app
spec:
  type: ClusterIP
  selector:
    app: eks-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  sessionAffinity: None
